language: bash
os: osx
before_script:
- brew update
- brew install shellcheck
- brew install shunit2
script:
- shellcheck bootstrap
- shellcheck macos-defaults
- echo "master master Europe/Paris ${TRAVIS_OS_NAME} n" | sh bootstrap
- echo "master master Europe/Paris ${TRAVIS_OS_NAME} y y" | sh bootstrap