name: shellcheck
on:
  pull_request:
    types: edited
  push:
    branches-ignore: main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install shellcheck shfmt
      - name: shellcheck
        run: shellcheck bootstrap
      - name: shfmt
        run: shfmt -s -i 2 -bn -ci -sr -kp bootstrap

